---
# file: roles/java/tasks/oracle8.yml

- name: add repo for java 8
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes
  changed_when: false

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  sudo: yes
  changed_when: false

- name: install java 8
  apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
  sudo: yes

- name: Java | Set JAVA_HOME
  lineinfile:
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-oracle'
    dest: /etc/environment
    state: present
    create: yes
